package org.cuit.app.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_relationship
 */
public class Relationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   监护人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.guardian
     *
     * @mbg.generated
     */
    private Integer guardian;

    /**
     * Database Column Remarks:
     *   老人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.elderly
     *
     * @mbg.generated
     */
    private Integer elderly;

    /**
     * Database Column Remarks:
     *   create_time
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationship.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.id
     *
     * @return the value of t_relationship.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.id
     *
     * @param id the value for t_relationship.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.guardian
     *
     * @return the value of t_relationship.guardian
     *
     * @mbg.generated
     */
    public Integer getGuardian() {
        return guardian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.guardian
     *
     * @param guardian the value for t_relationship.guardian
     *
     * @mbg.generated
     */
    public void setGuardian(Integer guardian) {
        this.guardian = guardian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.elderly
     *
     * @return the value of t_relationship.elderly
     *
     * @mbg.generated
     */
    public Integer getElderly() {
        return elderly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.elderly
     *
     * @param elderly the value for t_relationship.elderly
     *
     * @mbg.generated
     */
    public void setElderly(Integer elderly) {
        this.elderly = elderly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.create_time
     *
     * @return the value of t_relationship.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.create_time
     *
     * @param createTime the value for t_relationship.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.update_time
     *
     * @return the value of t_relationship.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.update_time
     *
     * @param updateTime the value for t_relationship.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relationship.delete_time
     *
     * @return the value of t_relationship.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relationship.delete_time
     *
     * @param deleteTime the value for t_relationship.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}