server:
  port: 8638
spring:
  application:
    name: elderly-care
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.113.185.11:3319/elderly-care?useSSL=false&useUnicode=yes&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5       # 初始线程数
      max-active: 20        # 最大线程数
      max-wait: 60000       # 最大等待时间
      time-between-eviction-runs-millis: 60000      # 最大空闲实践
      min-idle: 5           #最小线程数
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 47.113.185.11
    port: 6379
    password: epoch
    database: 1
    jedis:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 8
        max-wait: 10000
    timeout: 5000
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:

pagehelper:
  reasonable: true
  helper-dialect: mysql
mybatis-plus:
  type-aliases-package: org.cuit.app.entity,org.cuit.app.entity.vo
  mapper-locations: classpath:org/cuit/app/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

