package org.cuit.app.mapper;

import java.util.List;
import org.cuit.app.entity.Relationship;

public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationship
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationship
     *
     * @mbg.generated
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationship
     *
     * @mbg.generated
     */
    Relationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationship
     *
     * @mbg.generated
     */
    List<Relationship> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relationship
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Relationship record);
}